In [2]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
# corpus =['Lewis Yang', 'ada Yang']
vectorizer = CountVectorizer() #準備在記憶體之中
X = vectorizer.fit_transform(corpus) # 真正餵入資料轉換上述LIST成為   代碼表
# X.toarray(), np.sum(X.toarray(), axis=1)
print('vocabuary', '\n', vectorizer.get_feature_names_out()) # 單字 Tokenizer
print('Sentence to vector', '\n', X.toarray() )   # 代碼表轉換成矩陣  代碼表

from sklearn.metrics import pairwise
# print(pairwise.cosine_similarity( X.toarray()[0].reshape(-1,1),  
#                                   X.toarray()[1].reshape(-1,1)))
print(pairwise.cosine_similarity(X[0], X).ravel())

vocabuary 
 ['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
Sentence to vector 
 [[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]
[1.         0.79056942 0.54772256 1.        ]


In [ ]:
for d in range(len(corpus)):
    words = np.where( X.toarray()[d, :] ==0 , False, True) 
    print(np.array(vectorizer.get_feature_names_out())[words])

['document' 'first' 'is' 'the' 'this']
['document' 'is' 'second' 'the' 'this']
['and' 'is' 'one' 'the' 'third' 'this']
['document' 'first' 'is' 'the' 'this']


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
# corpus = [
#     'This is the first document.',
#     'This document is the second document.',
#     'And this is the third one.',
#     'Is this the first document?',
# ]
corpus =['Lewis Yang', 'Ada-Kuo', "Julia Li and BoBo Yang", 'Ada Yang']

vectorizer = CountVectorizer() #準備在記憶體之中
X = vectorizer.fit_transform(corpus) # 真正餵入資料轉換上述LIST成為   代碼表

print('vocabuary', '\n', vectorizer.get_feature_names_out()) # 單字 Tokenizer
print('Sentence to vector', '\n', X.toarray() )   # 代碼表轉換成矩陣  代碼表

vocabuary 
 ['ada' 'and' 'bobo' 'julia' 'kuo' 'lewis' 'li' 'yang']
Sentence to vector 
 [[0 0 0 0 0 1 0 1]
 [1 0 0 0 1 0 0 0]
 [0 1 1 1 0 0 1 1]
 [1 0 0 0 0 0 0 1]]


In [ ]:
import numpy as np
#print(dir(vectorizer))
text= ['I am lewis yang'] # 原文
data = vectorizer.transform(text).toarray() # 經過轉換
print(data) # 變成代碼表
vectorizer.inverse_transform(data) # 反代碼表成為文字

[[0 0 0 0 0 1 0 1]]


[array(['lewis', 'yang'], dtype='<U5')]

In [ ]:
# <4x9 sparse matrix of type '<class 'numpy.int64'>'
# 	with 21 stored elements in Compressed Sparse Row format>

In [ ]:
X.toarray()

array([[0, 0, 0, 0, 0, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 1]])

In [ ]:
np.array(vectorizer.get_feature_names_out()), X.toarray()[3].astype('bool')

(array(['ada', 'and', 'bobo', 'julia', 'kuo', 'lewis', 'li', 'yang'],
       dtype=object),
 array([ True, False, False, False, False, False, False,  True]))

In [ ]:
import numpy as np
# 根據 X.toarray() 對應出字典單字
words = np.array(vectorizer.get_feature_names_out())
for i in range(len(corpus)):
    print( words[(X.toarray()[i]).astype('bool')] )
# corpus =['Lewis Yang', 'Ada-Kuo', "Julia Li and BoBo Yang", 'Ada Yang']    

['lewis' 'yang']
['ada' 'kuo']
['and' 'bobo' 'julia' 'li' 'yang']
['ada' 'yang']


In [ ]:
import numpy as np
words = np.array(vectorizer.get_feature_names_out())
words

array(['ada', 'and', 'bobo', 'julia', 'kuo', 'lewis', 'li', 'yang'],
      dtype=object)

In [ ]:
words[(X.toarray())[0].astype('bool')]

array(['lewis', 'yang'], dtype=object)

In [ ]:
[i.split() for i in corpus]

[['Lewis', 'Yang'],
 ['Ada-Kuo'],
 ['Julia', 'Li', 'and', 'BoBo', 'Yang'],
 ['Ada', 'Yang']]

In [ ]:
#2-layer list comprehension 手動方式
corpus = [
    'This is the first document',
    'This document is the second document',
    'And this is the third one',
    'Is this the first document',
]
mydict = []
for i in corpus:
    for j in i.lower().split():
        mydict.append(j)
np.unique(mydict)

array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype='<U8')

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This is the first document',
    'This document is the second document',
    'And this is the third one',
    'Is this the first document',
]
vectorizer = CountVectorizer() #準備在記憶體之中
X = vectorizer.fit_transform(corpus) # 真正餵入資料轉換上述LIST成為   代碼表

print('vocabuary', '\n', vectorizer.get_feature_names_out()) # 單字 Tokenizer
print('Sentence to vector', '\n', X.toarray() )   # 代碼表轉換成矩陣  代碼表

vocabuary 
 ['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
Sentence to vector 
 [[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [ ]:
# 加入 sklearn 的 stopwords
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This is the first document',
    'This document is the second document',
    'And this is the third one',
    'Is this the first document',
]
vectorizer = CountVectorizer(stop_words='english') #準備在記憶體之中
X = vectorizer.fit_transform(corpus) # 真正餵入資料轉換上述LIST成為   代碼表

print('vocabuary', '\n', vectorizer.get_feature_names_out()) # 單字 Tokenizer
print('Sentence to vector', '\n', X.toarray() )   # 代碼表轉換成矩陣  代碼表

vocabuary 
 ['document' 'second']
Sentence to vector 
 [[1 0]
 [2 1]
 [0 0]
 [1 0]]


In [ ]:
# 根據 自己切字 找出唯一
np.unique([j for i in corpus for j in i.lower().split()])

array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype='<U8')

In [ ]:
# 自己切字
# 2-layer list comprehension 手動方式
corpus = [
    'This is the first document',
    'This document is the second document',
    'And this is the third one',
    'Is this the first document',
]

np.unique([j.lower() for i in corpus for j in i.split() ])

array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype='<U8')

In [ ]:
for i in corpus:
    for j in i.split():
        print(j)

This
is
the
first
document
This
document
is
the
second
document
And
this
is
the
third
one
Is
this
the
first
document


In [ ]:
# scikit-learn stopwords
from sklearn.feature_extraction import _stop_words as stop_words
'is' in  (stop_words.ENGLISH_STOP_WORDS)

True

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
# nltk stopwords
# !pip install nltk

from nltk.corpus import stopwords
english_stops = set(stopwords.words('english'))

allwords =  ['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
for a in allwords :
    if a in english_stops :
        print(a , ' in english_stop_words')

and  in english_stop_words
is  in english_stop_words
the  in english_stop_words
this  in english_stop_words
