In [ ]:
# tfidf : term() frequency -inverse document frequency
# 檢視該單字 在文章中出現次數(tf)與跨越文章出現次數(idf)

In [1]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics.pairwise import cosine_similarity

corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer = CountVectorizer() # 顯示單字出現的頻率
X = vectorizer.fit_transform(corpus)


print('vocabuary', '\n', vectorizer.get_feature_names_out())

print('Sentence to vector', '\n', X.toarray() )  

vocabuary 
 ['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
Sentence to vector 
 [[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [2]:
import numpy as np
# 根據 X.toarray() 對應出字典單字
words = np.array(vectorizer.get_feature_names_out())
for i in range(len(corpus)):
    print( words[(X.toarray()[i]).astype('bool')] )

['document' 'first' 'is' 'the' 'this']
['document' 'is' 'second' 'the' 'this']
['and' 'is' 'one' 'the' 'third' 'this']
['document' 'first' 'is' 'the' 'this']


In [3]:
words[X.toarray()[0].astype('bool')]

array(['document', 'first', 'is', 'the', 'this'], dtype=object)

In [4]:
X.toarray()

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 2, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]])

In [5]:
# 轉換成 tf idf
transformer = TfidfTransformer()

In [6]:
tfidf = transformer.fit_transform(X)
tfidf.toarray().shape # 四篇文章 所有的單字 
print(tfidf.toarray()) # 該部分類似 CountVectorizer() 顯示單字出現的頻率，加上權重

[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]
 [0.         0.6876236  0.         0.28108867 0.         0.53864762
  0.28108867 0.         0.28108867]
 [0.51184851 0.         0.         0.26710379 0.51184851 0.
  0.26710379 0.51184851 0.26710379]
 [0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


In [8]:
cosine_similarity(tfidf[0], tfidf).ravel() # 找出第幾篇 文章 跟其他的相似度(包含自己)

array([1.        , 0.64692568, 0.30777187, 1.        ])

In [ ]:
#     'This is the first document.',
#     'This document is the second document.',
#     'And this is the third one.',
#     'Is this the first document?',


In [9]:
# 根據文章找出哪一筆文章最相似
base = 3
similarity_subject = np.array(cosine_similarity(tfidf[base], tfidf)).ravel()
similarity_subject

array([1.        , 0.64692568, 0.30777187, 1.        ])

In [10]:
# 新文章步驟一
news = ['That one is my third document']
news_x = vectorizer.transform(news)
news_x.toarray()

array([[0, 1, 0, 1, 1, 0, 0, 1, 0]])

In [11]:
# 新文章步驟二
news_x_tfidf = transformer.transform( news_x ).toarray()
news_x_tfidf

array([[0.        , 0.38991559, 0.        , 0.31878155, 0.61087812,
        0.        , 0.        , 0.61087812, 0.        ]])

In [12]:
# 新文章步驟三
similarity_subject_news = np.array(cosine_similarity(news_x_tfidf, tfidf)).ravel()
similarity_subject_news

array([0.30561827, 0.35772104, 0.71050187, 0.30561827])

In [ ]:
corpus[np.argmax(similarity_subject_news)]

'And this is the third one.'

In [ ]:
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]