In [ ]:
# 請幫忙找 sushi 最接近的十個單字
# https://nlp.stanford.edu/data/glove.6B.zip

In [ ]:
glove = []
with open('glove.6B.100d.txt', encoding='utf-8') as f:
    glove = f.readlines()

In [ ]:
import numpy as np
glove_embedded = dict([ (line.split()[0], np.array(line.split()[1:], dtype='float32')) for line in glove])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
glove_embedded['sushi'] , glove_embedded['sashimi']
print(np.array(cosine_similarity(glove_embedded['sushi'].reshape(1,-1), glove_embedded['sashimi'].reshape(1,-1))).ravel())
print(np.array(cosine_similarity(glove_embedded['sushi'].reshape(1,-1), glove_embedded['dumping'].reshape(1,-1))).ravel())
print(np.array(cosine_similarity(glove_embedded['sushi'].reshape(1,-1), glove_embedded['sake'].reshape(1,-1))).ravel())

[0.7530954]
[0.22298916]
[0.29881832]


In [ ]:
words = list(glove_embedded.keys())
words[:10]

['the', ',', '.', 'of', 'to', 'and', 'in', 'a', '"', "'s"]

In [ ]:
# 利用 cosine_similarity 比對 指定單字與 所有單字的 空間距離
compare = np.array(cosine_similarity(glove_embedded['sushi'].reshape(1,-1), list(glove_embedded.values())  )).ravel()

In [ ]:
compare

array([ 0.0327284 ,  0.04962882,  0.05628538, ..., -0.03987219,
       -0.16023879, -0.30015308], dtype=float32)

In [ ]:
#argmax 
np.argmax(compare), words[21961]

(21961, 'sushi')

In [ ]:
pd.DataFrame.sort_values?


In [ ]:
%%time
# method 1
import pandas as pd
compare_df = pd.Series(compare).reset_index()
compare_df.columns = ['index', 'value']
for i in compare_df.sort_values(by ='value', ascending=False)[:10]['index'].values:
    print(i, words[i])
compare_df[:10]

694 taiwan
2545 mainland
132 china
5288 taiwanese
3497 taipei
729 hong
327 chinese
727 kong
942 beijing
9340 roc
Wall time: 55.9 ms


index     value
0      0  0.443996
1      1  0.432407
2      2  0.404640
3      3  0.405689
4      4  0.468503
5      5  0.444277
6      6  0.423423
7      7  0.401570
8      8  0.328433
9      9  0.444630

In [ ]:
#method 2 find index of top 3 (1, 4, 3) oder by value
#                0  1  2  3  4
###############################
data = np.array([1, 8, 3, 4 ,6])
###############################
#                0  2  3  4  1 
#[-3]                  3  4  1
#[-3][::-1]            1  4  3
np.argsort(data)[-3:][::-1]

array([1, 4, 3], dtype=int64)

In [ ]:
data = np.array([1, 8, 3, 4 ,6])
np.argsort(data)

array([0, 2, 3, 4, 1], dtype=int64)

In [ ]:
words_np = np.array(words)
words_np[ np.argsort(compare)[-10:][::-1] ]

array(['sushi', 'sashimi', 'seafood', 'gourmet', 'fried', 'restaurant',
       'cuisine', 'sandwiches', 'lobster', 'delicacies'], dtype='<U68')

In [ ]:
%%time
# 驗證
keyword = 'sushi'
compare = np.array(cosine_similarity(glove_embedded[keyword].reshape(1,-1), list(glove_embedded.values())  )).ravel()
words_np[ np.argsort(compare)[-20:][::-1] ]

Wall time: 406 ms


array(['beef', 'meat', 'pork', 'poultry', 'chicken', 'dairy', 'cow',
       'veal', 'imports', 'mutton', 'lamb', 'cattle', 'meats', 'milk',
       'corned', 'seafood', 'imported', 'offal', 'vegetables', 'pigs'],
      dtype='<U68')

In [ ]:
%%time
# 太久
a = [(np.array(cosine_similarity(glove_embedded['sushi'].reshape(1,-1),
                                 glove_embedded.get(i).reshape(1,-1))).ravel()) for i in glove_embedded.keys()]
a = sorted(a, reverse = True)
a[:10]


Wall time: 57.5 s


[array([0.99999994], dtype=float32),
 array([0.7530954], dtype=float32),
 array([0.6691842], dtype=float32),
 array([0.66598725], dtype=float32),
 array([0.621807], dtype=float32),
 array([0.6170368], dtype=float32),
 array([0.60895705], dtype=float32),
 array([0.6084705], dtype=float32),
 array([0.6040761], dtype=float32),
 array([0.6037608], dtype=float32)]

In [ ]:
%%time
#####################
# Final : Load data
#####################
import numpy as np
glove = []
with open('glove.6B.100d.txt', encoding='utf-8') as f:
    glove = f.readlines()
glove_embedded = dict([ (line.split()[0], np.array(line.split()[1:], dtype='float32')) for line in glove])    
words_np = np.array(words)
words = list(glove_embedded.keys())

Wall time: 11.6 s


In [ ]:
%%time
#####################
# Fina : Find top
####################
keyword = 'taiwan'
compare = np.array(cosine_similarity(glove_embedded[keyword].reshape(1,-1), list(glove_embedded.values())  )).ravel()
words_np[ np.argsort(compare)[-20:][::-1] ]

Wall time: 397 ms


array(['taiwan', 'mainland', 'china', 'taiwanese', 'taipei', 'hong',
       'chinese', 'kong', 'beijing', 'roc', 'chen', 'korea', 'singapore',
       'vietnam', 'thailand', 'korean', 'dprk', 'japan', 'shanghai',
       'kmt'], dtype='<U68')